services:
  # MongoDB service
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend (Node.js API)
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/prescripto
      - JWT_SECRET=supersecretkey
      - STRIPE_KEY=dummy_stripe_key
      - RAZORPAY_KEY=dummy_razorpay_key
    depends_on:
      - mongo

  # Frontend (React App for patients)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Admin (React App for doctors/admins)
  admin:
    build: ./admin
    container_name: admin
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  mongo_data:
